### ISSUE TITLE
PAA is slower than Cascade RCNN ？

### ISSUE THREAD

**Issue by XianYuZhiWang** [kkhoot/PAA#14]
Thank you for you job, I trained two model based on mmdetecton2 :1. Cascade rcnn fpn r50; 2.PAA fpn r50. When I tested those two model on 2080ti, Cascade FPS was  about 15, and the PAA FPS was about 10, it seem's one stage model PAA is slower than two stage model cascade , this is so weird, is that normal? And I take a glance at your paper ,but did not saw data about inference speed.

**Comment by kkhoot** [comment]
Hi, thanks for your interest. The inference speed depends on the number of objects in the input. If you care FPS, then I recommend  you to disable Score Voting. It is relatively slow since it is running on Python code. Please note that the slow speed of Score Voting is merely a implementation matter. It can be much faster when using Cython or running it on GPU, just like NMS.
