### ISSUE TITLE
Question about the hyper parameters of GMM

### ISSUE THREAD

**Issue by Chrisfsj2051** [kkhoot/PAA#19]
Hi @kkhoot , 

Thanks for your amazing and stable work!

I'm trying to implement PAA, but I'm confused about the argument `precisions_init`. What's the reason for not using the default value of this argument?

https://github.com/kkhoot/PAA/blob/65bde62e8b634cea75ad2bf171bcf45a8fe148d4/paa_core/modeling/rpn/paa/loss.py#L193

**Comment by kkhoot** [comment]
Hi, thanks for your interest!
The default init methods may also work well. The init mean/precision values in our paper are to make anchor scores are well separated with few (45) examples. If you perform EM with all the anchors, then I think it should be less sensitive with init methods or values. However, because of the speed issue, only 45 samples are collected for EM. So I set the mean values as min/max scores to make them easily separated. The precision values (1.0, 1.0) are empirically set, and I guess the exact value should not be important and other values can also work well.

**Comment by Chrisfsj2051** [comment]
Thanks!
