### ISSUE TITLE
Have you tried to use probability to reweight the loss？

### ISSUE THREAD

**Issue by jshilong** [kkhoot/PAA#7]
Hi, 
In the paper, after fit the GMM distribution,  you just devided all samples to pos and neg with threshold (you describe such process as easing the optimization ). 
Have you tried to calculate the real P_pos and P_neg (= 1 - P_pos)  to reweight the pos_loss and neg_loss of each sample? 
In my opinion  It seems more reasonable according to the theory.
Thanks.

**Comment by kkhoot** [comment]
Hi @jshilong. That is a good point. I haven't tried the approach you described. What I tried was to assign a cumulative prob. to an anchor so that anchors with higher scores get higher weights. This approach gave a similar but slightly lower performance.  I think the approach you described is worth a try. However, I am not 100% sure this will give a better performance, because at the early training iterations, the two GMM modes might overlap significantly, in that case the model can be confused in distinguishing pos and neg samples. The thresholding approach used in the paper can mitigate this situation IMO. But as I said I haven't tried this and you may be right at this. I would like to try the approach you mentioned in the near future. Thanks for your insightful point!

**Comment by feiyuhuahuo** [comment]
Hi, @jshilong.  Have you tried your idea?  Can it boost the performance?
Thanks.

**Comment by jshilong** [comment]
It did't work.

**Comment by kkhoot** [comment]
Closing as OP tried and answered the question.
